export { default as Signin } from "./Auth/Signin";
export { default as Signup } from "./Auth/Signup";
export { default as Header } from "./Header/Header";
export { default as MainSection } from "./MainSection/MainSection";
export { default as NewPost } from "./NewPost/NewPost";
export { default as Posts } from "./Posts/PostContainer";
export { default as Home } from "./Home/Home";
export { default as User } from "./User/User";
export { default as PostPage } from "./PostPage/PostPage";
